### ISSUE TITLE
Error in delete row

### ISSUE THREAD

**Issue by fanishe** [lfparis/airbase#14]
When I run this code from example:
```python
record = {"id": "recID",}
await table.delete_record(record)
```
Raises an Error
```python
Traceback (most recent call last):
  File "airtable/table.py", line 128, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "airtable/table.py", line 124, in main
    await table.delete_record(record)
  File "/hdd/gh/zhurbot/venv/lib/python3.8/site-packages/airbase/airtable.py", line 595, in delete_record
    message = record["fields"].get(self.primary_field_name) or record.get(
KeyError: 'fields'
```
I've read the code and modified the record:
```python
record = {'fields': {'id': 'recID'}, 'id': 'recID'}
await table.delete_record(record)

2021-08-27 13:41:38 (UTC/GMT +0300) (airbase.airtable): INFO - Deleted: recID
```

May be smth wrong with code?
```
➜ pip freeze
aiogram==2.14.3
aiohttp==3.7.4.post0
aiosqlite==0.17.0
airtable-async==0.0.1b9
async-timeout==3.0.1
attrs==21.2.0
Babel==2.9.1
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.4
idna==3.2
multidict==5.1.0
pyairtable==1.0.0
pytz==2021.1
requests==2.26.0
typing-extensions==3.10.0.0
urllib3==1.26.6
yarl==1.6.3

➜ python -V
Python 3.8.10

➜ pip --version
pip 21.1.3 from /hdd/gh/zhurbot/venv/lib/python3.8/site-packages/pip (python 3.8)
```
If you need some more info, I'll send

**Comment by lfparis** [comment]
`table.delete_record(record)` is expecting a dictionary with 2 keys: `id` and `fields` even though the `fields` key is not required for deleting a record or records.
look out for version **0.0.1b10** later this week that will allow delete methods to accept dictionaries with only the `id` key.

**Comment by lfparis** [comment]
See new [release](https://github.com/lfparis/airbase/releases/tag/0.0.1b10)
